### ISSUE TITLE
error no json object could be decoded

### ISSUE THREAD

**Issue by harveyphan** [romanvm/kodi.tvmaze.scrobbler#23]
Hi,

I am facing this issue: error no json object could be decoded when syncing.

--> End of Python script error report <--
ValueError: no json object could be decoded
File: /home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-lir
line 382, in raw_decode

Thanks

**Comment by romanvm** [comment]
Where is your debug log?

**Comment by harveyphan** [comment]
`                                                                      {u'label': u'Yellowstone (2018)',
                                                                       u'tvshowid': 30,
                                                                       u'uniqueid': {u'tvdb': u'341164',
                                                                                     u'unknown': u''}},
                                                                      {u'label': u'\u5927\u4fa0\u970d\u5143\u7532 Heroes S01',
                                                                       u'tvshowid': 38,
                                                                       u'uniqueid': {u'unknown': u''}},
                                                                      {u'label': u'\u6f02\u4eae\u4e66\u751f in a Class of Her Own S01',
                                                                       u'tvshowid': 37,
                                                                       u'uniqueid': {u'unknown': u''}}]}}
2020-09-10 21:06:28.395 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:244 - Pulling watched episodes from TVmaze
2020-09-10 21:06:28.402 T:4588   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
2020-09-10 21:06:28.403 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Avatar the Last Airbender S01 Amzn',
                                             u'tvshowid': 31,
                                             u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:28.405 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Cable Girls S05 Part 2 Nf',
                                             u'tvshowid': 2,
                                             u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:28.406 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Chernobyl S01 Amzn',
                                             u'tvshowid': 7,
                                             u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:28.407 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/17861"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:29.689 T:4698   DEBUG: PLEX.plexgdm: Recieved UDP packet from [('127.0.0.1', 42428)] containing [M-SEARCH * HTTP/1.1]
2020-09-10 21:06:29.690 T:4698   DEBUG: PLEX.plexgdm: Detected client discovery request from ('127.0.0.1', 42428).  Replying
2020-09-10 21:06:29.690 T:4698   DEBUG: PLEX.plexgdm: Sending registration data HTTP/1.0 200 OK
2020-09-10 21:06:30.191 T:4698   DEBUG: PLEX.plexgdm: Recieved UDP packet from [('192.168.50.125', 46713)] containing [M-SEARCH * HTTP/1.1]
2020-09-10 21:06:30.191 T:4698   DEBUG: PLEX.plexgdm: Detected client discovery request from ('192.168.50.125', 46713).  Replying
2020-09-10 21:06:30.192 T:4698   DEBUG: PLEX.plexgdm: Sending registration data HTTP/1.0 200 OK
2020-09-10 21:06:30.300 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:30.300 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:30.301 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 17861:
                                            []
2020-09-10 21:06:30.301 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Dark S03 Nf', u'tvshowid': 3, u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:30.302 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/35017"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:30.590 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:30.591 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:30.591 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 35017:
                                            []
2020-09-10 21:06:30.592 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Doctor Who Season 1 S01',
                                             u'tvshowid': 14,
                                             u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:30.594 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/1270"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:30.891 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:30.892 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:30.893 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 1270:
                                            []
2020-09-10 21:06:30.894 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Hanna S02 Amzn', u'tvshowid': 10, u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:30.895 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/891"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:31.795 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:31.795 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:31.795 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 891:
                                            []
2020-09-10 21:06:31.796 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/347"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:32.093 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:32.094 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:32.094 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 347:
                                            []
2020-09-10 21:06:32.096 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/263"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:32.382 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:32.382 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:32.382 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 263:
                                            []
2020-09-10 21:06:32.383 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/28893"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:32.680 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:32.680 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:32.681 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 28893:
                                            []
2020-09-10 21:06:32.683 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/694"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:32.970 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:32.970 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:32.971 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 694:
                                            []
2020-09-10 21:06:32.971 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'Normal People S01 Hulu',
                                             u'tvshowid': 24,
                                             u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:32.972 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:254 - Unable to determine TVmaze id from show info: {u'label': u'On Lie Game', u'tvshowid': 36, u'uniqueid': {u'unknown': u''}}
2020-09-10 21:06:32.973 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "https://api.tvmaze.com/v1/scrobble/shows/2094"... method: get, parameters:
                                            {'params': {u'embed': u'episode', u'type': 0}}
2020-09-10 21:06:33.261 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:121 - API response:
                                            []
2020-09-10 21:06:33.261 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:168 - API response:
                                            []
2020-09-10 21:06:33.263 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - scrobbling_service.py:268 - Episodes from TVmaze for 2094:
                                            []
2020-09-10 21:06:33.264 T:11741   DEBUG: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:116 - Calling URL "http://api.tvmaze.com/lookup/shows"... method: get, parameters:
                                            {'params': {u'thetvdb': u'218001'}}
2020-09-10 21:06:33.829 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - tvmaze_api.py:120 - TVmaze returned error 404
2020-09-10 21:06:34.031 T:11737    INFO: easy_acquire - Created session to http://www.msftncsi.com
2020-09-10 21:06:34.039 T:11741   ERROR: script.tvmaze.scrobbler [v.1.0.0] - kodi_service.py:280 - 
                                            *********************************** Unhandled exception detected ***********************************
                                            ====================================================================================================
                                                                                       Diagnostic info
                                            ----------------------------------------------------------------------------------------------------
                                            Exception type  : <type 'exceptions.ValueError'>
                                            Exception value : No JSON object could be decoded
                                            System info     : ('Linux', 'localhost', '4.9.140-tegra-g5eb7ca7547d4', '#2 SMP PREEMPT Fri Jul 31 18:28:50 PDT 2020', 'aarch64', '')
                                            Python version  : 2.7.15 (default, Jul 28 2020, 06:13:04)  [GCC 4.2.1 Compatible Android (4751641 based on r328903) Clang 7.0.2 (https://a
                                            OS info         : Busy
                                            Kodi version    : 18.8 (18.8.0) Git:20200727-45686bddb1
                                            File            : /home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/decoder.py:382
                                            sys.argv        : ['script.py']
                                            ----------------------------------------------------------------------------------------------------
                                            sys.path:
                                            ['',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.dateutil/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodi-six/libs',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.pyqrcode/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.pyxbmct/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.six/lib',
                                             '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib',
                                             '/',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python27.zip',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/site-packages',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/plat-linux2',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/lib-tk',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/lib-old',
                                             '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/lib-dynload']
                                            ----------------------------------------------------------------------------------------------------
                                            Code context:
                                            
                                            ----------------------------------------------------------------------------------------------------
                                            Global variables:
                                            BACKSLASH = {'"': u'"',
                                             '/': u'/',
                                             '\\': u'\\',
                                             'b': u'\x08',
                                             'f': u'\x0c',
                                             'n': u'\n',
                                             'r': u'\r',
                                             't': u'\t'}
                                            DEFAULT_ENCODING = 'utf-8'
                                            FLAGS = 88
                                            JSONArray = <function JSONArray at 0x2bcc90c920>
                                            JSONDecoder = <class 'json.decoder.JSONDecoder'>
                                            JSONObject = <function JSONObject at 0x2bcc90c8a0>
                                            NaN = nan
                                            NegInf = -inf
                                            PosInf = inf
                                            STRINGCHUNK = <_sre.SRE_Pattern object at 0x2bcae03060>
                                            WHITESPACE = <_sre.SRE_Pattern object at 0x2bcc98cee0>
                                            WHITESPACE_STR = ' \t\n\r'
                                            _CONSTANTS = {'-Infinity': -inf, 'Infinity': inf, 'NaN': nan}
                                            _decode_uXXXX = <function _decode_uXXXX at 0x2bcc90c7a0>
                                            _floatconstants = <function _floatconstants at 0x2bcc90c5a0>
                                            c_scanstring = <built-in function scanstring>
                                            errmsg = <function errmsg at 0x2bcc90c720>
                                            linecol = <function linecol at 0x2bcc90c6a0>
                                            py_scanstring = <function py_scanstring at 0x2bcc90c820>
                                            re = <module 're' from '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/re.pyo'>
                                            scanner = <module 'json.scanner' from '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/json/scanner.pyo'>
                                            scanstring = <built-in function scanstring>
                                            struct = <module 'struct' from '/data/app/org.xbmc.kodi-q9q9XPQTTsw1HIhgrnn4fQ==/base.apk/assets/python2.7/lib/python2.7/struct.pyo'>
                                            sys = <module 'sys' (built-in)>
                                            ----------------------------------------------------------------------------------------------------
                                            Local variables:
                                            idx = 0
                                            s = u''
                                            self = <json.decoder.JSONDecoder object at 0x2bc6b4f520>
                                            ====================================================================================================
                                            **************************************** End diagnostic info ***************************************
2020-09-10 21:06:34.040 T:11741   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/script.py", line 40, in <module>
                                                main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/script.py", line 35, in main
                                                action()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/scrobbling_service.py", line 350, in sync_all_episodes
                                                _pull_watched_episodes(tv_shows)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/scrobbling_service.py", line 251, in _pull_watched_episodes
                                                tvmaze_id = _get_tvmaze_id(show)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/scrobbling_service.py", line 185, in _get_tvmaze_id
                                                unique_id.show_id, unique_id.provider, kodi_show_info['tvshowid'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/scrobbling_service.py", line 168, in _load_and_store_tvmaze_id
                                                show_info = tvmaze.get_show_info_by_external_id(show_id, provider)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 238, in get_show_info_by_external_id
                                                response = _call_common_api(SHOW_LOOKUP_PATH, 'get', params=params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 137, in _call_common_api
                                                response = _send_request(url, method, **requests_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/libs/tvmaze_api.py", line 121, in _send_request
                                                logger.debug('API response:\n{}'.format(pformat(response.json())))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-09-10 21:06:34.040 T:11741   DEBUG: onExecutionDone(31, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvmaze.scrobbler/script.py)
2020-09-10 21:06:34.041 T:4588   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-09-10 21:06:34.159 T:11741    INFO: Python interpreter stopped`

**Comment by romanvm** [comment]
Should be fixed in the latest release.
